version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - pg-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - pg-network
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    volumes:
      - pg-data:/var/lib/postgresql/data
    command: >
      bash -c "docker-entrypoint.sh postgres & sleep 5 && pg_restore -U docker -d db /app/database/init.sql && tail -f /dev/null"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    networks:
      - pg-network

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pg-admin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - pg-network

networks:
  pg-network:

volumes:
  pg-data: